# ~/.bashrc

# Colors
export TERM=xterm-256color

# Prompt: green user@host, blue cwd
# Hardcoded hostname since guest can't call hostname
export PS1='\[\033[1;32m\]guest\[\033[0m\]@\[\033[1;36m\]cli.yutarowatanabe.com\[\033[0m\]:\[\033[1;34m\]\w\[\033[0m\]\$ '

# Color aliases
alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias grep='grep --color=auto'
alias tree='tree -C'

# Navigation
alias ..='cd ..'
alias ...='cd ../..'

# The only custom commands
alias help='cat ~/README.md'
alias exit='sudo poweroff'

# Welcome message on every login
cat ~/README.md
